Adds task transform application
spring-cloud/spring-cloud-stream-app-starters pull request #226
Opened 2016-09-26 14:27 UTC by cppwfs

resolves #203

2016-09-26 16:05 UTC, artembilan commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/ParsingUtils.java
> + * Provides utility methods for formatting and parsing deployment properties.
Looks like this class parses not only "deployment properties", but also "commandLineArgs".
In addition it is intended for public usage. Plus its name is so generic. 
Maybe `TaskLaunchRequestParser`?..
Although this class can be fully moved as a bunch of private methods to the `TasklaunchrequestTransformProcessorConfiguration`

2016-09-26 16:07 UTC, artembilan commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> + * A transform that takes the maven repository coordinates, command line
A transform**er**

2016-09-26 16:09 UTC, artembilan commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> +		if(StringUtils.hasText(processorProperties.getDataSourceUrl())){
Code style nit-pick: whitespace before `{`.
There are many other similar code style issues.
But, eh, that is minor and can be fixed with simple reformat during merge.

2016-09-26 16:10 UTC, artembilan requested changes

2016-09-26 16:10 UTC, artembilan commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> +		return new GenericMessage<TaskLaunchRequest>(request);
I'm not sure if there is some environment in SCSt which should be supplied with some specific header, but I don't see reason here to instantiate `Message` ourselves. More over we don't provide any particular header.
OTOH and it is my main concern here: if `transformer` returns a `Message<?>` it doesn't populate any additional headers.
So, just returning `request` will make a day for you!
The same `Message<?>` as a further logic you have. Plus we carry headers if that.

2016-09-26 16:10 UTC, artembilan commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorProperties.java
> +	 * Comma delimited list of deployment properties to be applied to the
"Space delimited", " Comma delimited"...

Do you have any plans for any other delimiter styles in other options? :wink: 

I mean what is the point of the mix if we are here in the options for one application?
Thanks

2016-09-26 16:23 UTC, cppwfs commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> +		return new GenericMessage<TaskLaunchRequest>(request);
Sounds good to me.  Code will be updated to return the request.

2016-09-26 16:24 UTC, cppwfs commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorProperties.java
> +	 * Comma delimited list of deployment properties to be applied to the
This is to remain consistent in how a user will utilize tasks.  i.e. command line parameters are  space delimited while deployment properties are comma delimited.   We could choose just one, but in this case I chose to be consistent.

2016-09-26 16:25 UTC, cppwfs commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/ParsingUtils.java
> + * Provides utility methods for formatting and parsing deployment properties.
Will move these methods into the config as private methods.

2016-09-26 17:52 UTC, cppwfs commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> +		if(StringUtils.hasText(processorProperties.getDataSourceUrl())){
oops :-)

2016-09-29 21:48 UTC, mminella commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> +		properties.put("payload", message);
Why is this here?

2016-09-30 01:27 UTC, cppwfs commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> +		properties.put("payload", message);
we can drop it.  But thought it could be used by a task downstream.

2016-10-04 15:42 UTC, ilayaperumalg commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/README.adoc
> +The **$$filter$$** $$processor$$ has the following options:
This should be `tasklaunchrequest`

2016-10-04 20:18 UTC, cppwfs commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java
> +		properties.put("payload", message);
Payload no longer added to properties.

2016-10-04 20:18 UTC, cppwfs commented on processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/README.adoc
> +The **$$filter$$** $$processor$$ has the following options:
updated

2016-10-14 12:27 UTC, ilayaperumalg commented
LGTM, merging.

2016-10-14 12:28 UTC, ilayaperumalg commented
Squashed the commits, rebased and merged as  ca2dc8f

2016-10-14 12:28 UTC, closed without merging